version: '3'

services:
  gzweb:
    image: gzweb:latest
    networks:
      - gzweb_network
    ports:
      - "8080:8080"
    environment:
      - N_ROBOTS=3
      - WORLD=inspection

  warthog_joystick:
    image: warthog_joystick:latest
    networks:
      - gzweb_network
    ports:
      - "8081:80"

networks:
  gzweb_network:
    driver: bridge
