version: '3.8'

services:
  app:
    build: .
    container_name: go-gazebo
    command: -redis-host redis -container-ttl 120 -pool-size 1 -max-containers 10
    ports:
      - 9010:9010
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis-alpine

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command: --api.insecure=true --log.level=DEBUG --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

networks:
  traefik:
    name: traefik-net