version: '3.8'

services:
  app:
    build: .
    container_name: go-gazebo
    command: -api-key s3cr3t -container-image gzweb:latest -container-ttl 120 -host 0.0.0.0 -max-containers 3 -pool-size 1 -port 9010 -redis-host redis -redis-port 6379 -traefik-http-router-domain gazebo.test
    ports:
      - 9010:9010
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis-alpine

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command: --api.insecure=true --log.level=DEBUG --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

networks:
  traefik:
    name: traefik-net